# Generated by Django 4.1.4 on 2023-01-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('vid', models.CharField(max_length=200)),
                ('population', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images')),
                ('name_1', models.CharField(max_length=200)),
                ('price_1', models.IntegerField(default=0)),
                ('image_1', models.ImageField(upload_to='images')),
                ('name_2', models.CharField(max_length=200)),
                ('price_2', models.IntegerField(default=0)),
                ('image_2', models.ImageField(upload_to='images')),
                ('name_3', models.CharField(max_length=200)),
                ('price_3', models.IntegerField(default=0)),
                ('image_3', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': '無料ゲームリスト',
                'verbose_name_plural': '無料ゲームリスト',
            },
        ),
    ]
